### ISSUE TITLE
Z issue on probe 

### ISSUE THREAD

**Issue by dixon8322** [flyfisher604/mpcnc_post_processor#13]
When I start a cut I auto home x0y0z80 I load gcode  first g92 x0 y0 z0  then z probe  but the machine tries to travel up but z is already home at max any thoughts maybe g92 only x and y then z gets set on z probe to g38.2 z0.102

**Comment by flyfisher604** [comment]
Can you try to recreate the problem with a few lines of sample GCode?

Attach as a comment with explanation of expected result and what actually happens. 

Thx.

**Comment by flyfisher604** [comment]
Do you see an issue in the GCode produced by the post processor? I suspect the issue is with the micro-controller you are using. If the GCode looks ok after it finishes then it is not the post processor. That said, the PP does bend things around to make things behave, maybe I got it wrong. Looking forward to seeing a sample file. 

To make the sample, generate the output and then edit away/delete as much as you can that still creates the problem. 

Are you using Marlin?
